
version: 2

models:

  - name: mart_finance_165
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_166
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_167
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_171
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_172
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_174
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_177
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_183
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_186
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_finance_196
    description: "Mart layer model for finance domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count
