
version: 2

models:

  - name: raw_customer_007
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_020
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_021
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_022
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_023
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_024
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_customer_035
    description: "Raw layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2
