
version: 2

models:

  - name: raw_finance_000
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_003
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_008
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_009
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_011
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_013
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_017
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_018
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_031
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_034
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_036
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_finance_039
    description: "Raw layer model for finance domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2
