
version: 2

models:

  - name: mart_product_160
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_161
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_164
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_170
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_176
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_179
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_product_192
    description: "Mart layer model for product domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count
