
version: 2

models:

  - name: staging_customer_043
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_046
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_047
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_048
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_051
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_056
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_057
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_074
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_081
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_093
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_customer_098
    description: "Staging layer model for customer domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2
