airflow_db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gp21411
      user: HEMKUMARCHHEDA
      password: HKc@8010
      role: HEMKUMARCHHEDA
      database: SANDBOX
      warehouse: HUMANS
      schema: HEMKUMARCHHEDA
      threads: 4
      region: us-east-1