
version: 2

sources:

  - name: sales
    database: SANDBOX
    schema: HEMKUMARCHHEDA
    tables:

      - name: source_table_1
        description: Raw data source for sales domain, table 1
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_2
        description: Raw data source for sales domain, table 2
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_3
        description: Raw data source for sales domain, table 3
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_4
        description: Raw data source for sales domain, table 4
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_5
        description: Raw data source for sales domain, table 5
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

  - name: marketing
    database: SANDBOX
    schema: HEMKUMARCHHEDA
    tables:

      - name: source_table_1
        description: Raw data source for marketing domain, table 1
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_2
        description: Raw data source for marketing domain, table 2
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_3
        description: Raw data source for marketing domain, table 3
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_4
        description: Raw data source for marketing domain, table 4
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_5
        description: Raw data source for marketing domain, table 5
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

  - name: finance
    database: SANDBOX
    schema: HEMKUMARCHHEDA
    tables:

      - name: source_table_1
        description: Raw data source for finance domain, table 1
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_2
        description: Raw data source for finance domain, table 2
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_3
        description: Raw data source for finance domain, table 3
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_4
        description: Raw data source for finance domain, table 4
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_5
        description: Raw data source for finance domain, table 5
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

  - name: product
    database: SANDBOX
    schema: HEMKUMARCHHEDA
    tables:

      - name: source_table_1
        description: Raw data source for product domain, table 1
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_2
        description: Raw data source for product domain, table 2
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_3
        description: Raw data source for product domain, table 3
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_4
        description: Raw data source for product domain, table 4
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_5
        description: Raw data source for product domain, table 5
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

  - name: customer
    database: SANDBOX
    schema: HEMKUMARCHHEDA
    tables:

      - name: source_table_1
        description: Raw data source for customer domain, table 1
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_2
        description: Raw data source for customer domain, table 2
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_3
        description: Raw data source for customer domain, table 3
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_4
        description: Raw data source for customer domain, table 4
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3

      - name: source_table_5
        description: Raw data source for customer domain, table 5
        columns:
          - name: id
            description: Primary key
          - name: name
            description: Entity name
          - name: created_at
            description: Creation timestamp
          - name: value_1
            description: Metric 1
          - name: value_2
            description: Metric 2
          - name: value_3
            description: Metric 3
