
version: 2

models:

  - name: mart_sales_173
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_175
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_178
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_185
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_193
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_194
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_195
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_198
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_sales_199
    description: "Mart layer model for sales domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count
