
version: 2

models:

  - name: raw_product_005
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_006
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_010
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_012
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_014
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_015
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_029
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2

  - name: raw_product_038
    description: "Raw layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: metric_1
        description: Metric 1
      - name: metric_2
        description: Metric 2
