
version: 2

models:

  - name: mart_marketing_162
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_marketing_169
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_marketing_188
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_marketing_190
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_marketing_191
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count

  - name: mart_marketing_197
    description: "Mart layer model for marketing domain"
    columns:

      - name: name
        description: Entity name
      - name: latest_update
        description: Latest update timestamp
      - name: total_metric_1
        description: Total metric 1
      - name: avg_metric_2
        description: Average metric 2
      - name: total_records
        description: Total records count
