
version: 2

models:

  - name: staging_product_044
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_050
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_052
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_053
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_054
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_055
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_068
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_070
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_072
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_076
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_077
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_082
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_083
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_088
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_094
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_096
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_product_097
    description: "Staging layer model for product domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2
