
version: 2

models:

  - name: staging_sales_042
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_058
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_066
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_069
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_075
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_085
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_087
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2

  - name: staging_sales_089
    description: "Staging layer model for sales domain"
    columns:

      - name: id
        description: Primary key
      - name: name
        description: Entity name
      - name: created_at
        description: Creation timestamp
      - name: total_metric_1
        description: Sum of metric 1
      - name: avg_metric_2
        description: Average of metric 2
